package com.example.moneyusage.components

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*

/**
 * Get all the amount description dialog icons
 */
fun dialogIcons() = mapOf(
    "Agriculture" to Icons.Default.Agriculture,
    "Balance" to Icons.Default.Balance,
    "AttachMoney" to Icons.Default.AttachMoney,
    "AccountBalance" to Icons.Default.AccountBalance,
    "AccountBalanceWallet" to Icons.Default.AccountBalanceWallet,
    "Payments" to Icons.Default.Payments,
    "TrendingUp" to Icons.Default.TrendingUp,
    "Work" to Icons.Default.Work,
    "Business" to Icons.Default.Business,
    "Storefront" to Icons.Default.Storefront,
    "LocalGroceryStore" to Icons.Default.LocalGroceryStore,
    "EmojiTransportation" to Icons.Default.EmojiTransportation,
    "CleaningServices" to Icons.Default.CleaningServices,
    "FastFood" to Icons.Default.Fastfood,
    "Water" to Icons.Default.Water,
    "Payment" to Icons.Default.Payment,
    "Sell" to Icons.Default.Sell,
    "DesktopMac" to Icons.Default.DesktopMac,
    "Paid" to Icons.Default.Paid,
    "Description" to Icons.Default.Description,
    "Build" to Icons.Default.Build,
    "Laptop" to Icons.Default.Laptop,
    "DesktopWindows" to Icons.Default.DesktopWindows,
    "Tablet" to Icons.Default.Tablet,
    "PhoneAndroid" to Icons.Default.PhoneAndroid,
    "PhoneIphone" to Icons.Default.PhoneIphone,
    "SportsMotorsports" to Icons.Default.SportsMotorsports,
    "Motorcycle" to Icons.Default.Motorcycle,
    "Chair" to Icons.Default.Chair,
    "Cake" to Icons.Default.Cake,
    "CameraAlt" to Icons.Default.CameraAlt,
    "Camera" to Icons.Default.Camera,
    "CarRental" to Icons.Default.CarRental,
    "CarRental" to Icons.Default.Carpenter,
    "CastForEducation" to Icons.Default.CastForEducation,
    "CreditCard" to Icons.Default.CreditCard,
    "Savings" to Icons.Default.Savings,
    "Store" to Icons.Default.Store,
    "Hotel" to Icons.Default.Hotel,
    "House" to Icons.Default.House,
    "LocalPizza" to Icons.Default.LocalPizza,
    "FreeBreakfast" to Icons.Default.FreeBreakfast,
    "LocalGroceryStore" to Icons.Default.LocalGroceryStore,
    "Wallet" to Icons.Default.Wallet,
    "Watch" to Icons.Default.Watch,
    "AirplaneTicket" to Icons.Default.AirplaneTicket,
    "Coffee" to Icons.Default.Coffee,
    "Restaurant" to Icons.Default.Restaurant,
    "Atm" to Icons.Default.Atm,
    "Bed" to Icons.Default.Bed,
    "CarRepair" to Icons.Default.CarRepair,
)